[package]
name = "extended-einsum"
version = "0.1.0"
authors = ["Michael Hoy <mch.hoy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extended-einsum-macros = {path = "../extended-einsum-macros"}
itertools = "0.10.1"
ndarray = "0.15.3"

